GET http://127.0.0.1:8000/api/profiles/ HTTP/1.1
Accept: application/json


POST http://127.0.0.1:8000/api/profiles/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "profile_picture": "http://example.com/path/to/profile-picture.jpg"
}

GET http://127.0.0.1:8000/api/profiles/1/ HTTP/1.1
Accept: application/json

PUT http://127.0.0.1:8000/api/profiles/1/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@newdomain.com"
}

PUT http://127.0.0.1:8000/api/profiles/1/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@newdomain.com"
}

DELETE http://127.0.0.1:8000/api/profiles/1/ HTTP/1.1
